FROM python:3.9-slim

# dependências
RUN apt-get update && \
    apt-get -y install \
    build-essential \
    libpq-dev \
    libaio1 \
    git

RUN rm -rf /var/lib/apt/lists/*

RUN mkdir /code
WORKDIR /code

# pacotes
ADD requirements.txt /code
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# inicia development server ao iniciar o container
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

