"""first migration

Revision ID: d06d20e06bcd
Revises: 
Create Date: 2022-01-04 22:49:18.296056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06d20e06bcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    transaction_type_table = op.create_table('transaction_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('is_enter', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(transaction_type_table, [
        {"id":1,"name":"Débito", "is_enter":True, "symbol":"+"},
        {"id":2,"name":"Boleto", "is_enter":False, "symbol":"-"},
        {"id":3,"name":"Financiamento", "is_enter": 	False 	, "symbol":"-"},
        {"id":4,"name":"Crédito", "is_enter":True, "symbol":"+"},
        {"id":5,"name":"Recebimento Empréstimo", "is_enter":True, "symbol":"+"},
        {"id":6,"name":"Vendas", "is_enter":True,"symbol":"+"},
        {"id":7,"name":"Recebimento TED", "is_enter":True, "symbol":"+"},
        {"id":8,"name":"Recebimento DOC", "is_enter":True, "symbol":"+"},
        {"id":9,"name":"Aluguel", "is_enter":False,"symbol":"-"}
    ])
    op.create_index(op.f('ix_transaction_types_id'), 'transaction_types', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('time_at', sa.Time(timezone=True), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('cpf', sa.BigInteger(), nullable=True),
    sa.Column('card', sa.String(), nullable=True),
    sa.Column('transaction_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['transaction_type_id'], ['transaction_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_transaction_types_id'), table_name='transaction_types')
    op.drop_table('transaction_types')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
